### ISSUE TITLE
Is YTD safe to use?

### ISSUE THREAD

**Issue by kwaka77** [ibv/YTD#46]
I tried to check YTD binaries with virustotal.com and 6 of 72 virus engines found some kind of trojan or malicious code in setup.exe app. All tried version of YTD were affected eg. YTD-1.65.zip, old ytd-1.59-source.zip, ytd-1.59-lite.zip, ytd-1.59.zip, YTD-master.zip.  The ytd.exe itself was clean.

**Comment by ibv** [comment]
Hi,
**setup.exe** is the code of the original author of YTD, it is used to install and create a shortcut on the desktop, 
the code is written in assembly, in the directory Setup, maybe some constructs in the code 
confuse the AV soft so that setup.exe is considered infected.
New versions of YTD are used to install **Inno Setup** by Jordan Russell.
https://jrsoftware.org/isinfo.php

Regards
Ibv
